server.port=8080

# Application Name
spring.application.name=invoice-generator-backend

# Database Configuration
spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/invoice_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:root}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
